### ISSUE TITLE
当alias没有添加的时候，报错日志无法看出是没有添加对应的alias，建议优化错误日志。提示：对应的alias未添加。

### ISSUE THREAD

**Issue by junerver** [junerver/ComposeHooks#10]
### Discussed in https://github.com/junerver/ComposeHooks/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **danatechgithub4** May  9, 2024</sup>
```
java.lang.NullPointerException
                                                                                                    	at com.example.myapplication.UseReduxTestKt.UseReduxFetch(UseReduxTest.kt:591)
                                                                                                    	at com.example.myapplication.ComposableSingletons$UseReduxTestKt$lambda-1$1.invoke(UseReduxTest.kt:60)
                                                                                                    	at com.example.myapplication.ComposableSingletons$UseReduxTestKt$lambda-1$1.invoke(UseReduxTest.kt:56)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at xyz.junerver.compose.hooks.useredux.ReduxProviderKt$ReduxProvider$2.invoke(ReduxProvider.kt:47)
                                                                                                    	at xyz.junerver.compose.hooks.useredux.ReduxProviderKt$ReduxProvider$2.invoke(ReduxProvider.kt:46)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	at xyz.junerver.compose.hooks.UseContextKt$createContext$1.Provider(useContext.kt:34)
                                                                                                    	at xyz.junerver.compose.hooks.useredux.ReduxProviderKt.ReduxProvider(ReduxProvider.kt:46)
                                                                                                    	at com.example.myapplication.UseReduxTestKt.UseReduxTest(UseReduxTest.kt:56)
                                                                                                    	at com.example.myapplication.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:50)
                                                                                                    	at com.example.myapplication.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:34)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
```</div>

错误使用 `!!` 非空断言，导致在map[alias] 为空时不能正确触发抛出 registerErr

**Comment by junerver** [comment]
fix: [🧑‍💻: More friendly exception message](https://github.com/junerver/ComposeHooks/commit/3b3445961bc485281c71bbc2060865f20135a9e3)
