### ISSUE TITLE
升级2.0.0版本后`useEvent`相关hook抛出转型异常

### ISSUE THREAD

**Issue by junerver** [junerver/ComposeHooks#24]
### 复现过程：
运行项目，进入`useEvent` ，点击 `refresh` 按钮后 crash，异常如下：
> FATAL EXCEPTION: main
Process: xyz.junerver.composehooks, PID: 17180
java.lang.ClassCastException: java.lang.Object[] cannot be cast to kotlin.Unit
	at xyz.junerver.composehooks.example.UseEventExampleKt$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at xyz.junerver.compose.hooks.TypesKt.invoke(types.kt:38)
	at xyz.junerver.composehooks.example.UseEventExampleKt$Container$$inlined$useEventPublish$1.invoke(useEvent.kt:108)
	at xyz.junerver.composehooks.example.UseEventExampleKt$Container$$inlined$useEventPublish$1.invoke(useEvent.kt:104)
	at xyz.junerver.composehooks.example.UseEventExampleKt.Container$lambda$4$lambda$2$lambda$1(UseEventExample.kt:36)
	at xyz.junerver.composehooks.example.UseEventExampleKt.$r8$lambda$A5YqchR-ul7zIwnmkLsrw1RSolc(Unknown Source:0)
	at xyz.junerver.composehooks.example.UseEventExampleKt$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
	at xyz.junerver.composehooks.ui.component.TButtonKt.TButton$lambda$0(TButton.kt:29)
	at xyz.junerver.composehooks.ui.component.TButtonKt.$r8$lambda$gECPPYeg3VdXcnjdqpNWnBWU_hI(Unknown Source:0)
	at xyz.junerver.composehooks.ui.component.TButtonKt$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:987)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:981)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:947)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:795)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:303)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:113)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1576)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1527)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1466)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:765)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:2013)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4180)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:697)
	at android.view.View.dispatchPointerEvent(View.java:13967)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6489)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6284)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5692)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5850)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5700)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5907)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5692)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5673)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8857)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8777)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8730)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9117)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:239)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:363)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
        at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@db9cee5, androidx.compose.runtime.BroadcastFrameClock@f450dba, StandaloneCoroutine{Cancelling}@271b46b, AndroidUiDispatcher@5249bc8]

该问题在 kotlin 2.0 之前不发生，推测为升级2.0导致

**Comment by junerver** [comment]
已修复。修复版本为：`2.0.1`
